# Generated by Django 6.1.1 on 2026-09-23 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('tipo_acervo', models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico')], default='fisico', max_length=10)),
                ('categoria', models.CharField(choices=[('000', '000 – Generalidades e Informação'), ('100', '100 – Filosofia e Psicologia'), ('200', '200 – Religião e Teologia'), ('300', '300 – Ciências Sociais e Direito'), ('400', '400 – Linguística e Idiomas'), ('500', '500 – Ciências Puras (Exatas e Naturais)'), ('600', '600 – Ciências Aplicadas (Tecnologia)'), ('700', '700 – Artes e Recreação'), ('800', '800 – Literatura'), ('900', '900 – História e Geografia')], default='000', max_length=3)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='acervo.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonio', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado'), ('manutencao', 'Em manutenção')], default='disponivel', max_length=15)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='acervo.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_prevista_devolucao', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('valor_multa_diaria', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='acervo.exemplar')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='acervo.membro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='acervo.livro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='acervo.membro')),
            ],
            options={
                'ordering': ['data_reserva'],
            },
        ),
    ]
