# Generated by Django 6.1.1 on 2026-09-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="imagem_url",
            field=models.URLField(blank=True, verbose_name="URL da imagem"),
        ),
        migrations.AddField(
            model_name="livro",
            name="imagem_url",
            field=models.URLField(blank=True, verbose_name="URL da imagem (capa)"),
        ),
    ]
